apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
  labels:
    app: final-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-project
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: final-project
    spec:
      containers:
        - name: finalproject 
          image: phatryo99/finalproject:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: final-project-service
spec:
  type: LoadBalancer
  selector:
    app: final-project
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP  
