Description: >
  CloudFormation for creating EKS clusters
Parameters:
  EnvironmentName:
    Description: Enviroment name
    Type: String

  EKSClusterName:
    Description: EKS Cluster name
    Type: String
    Default: FinalProjectEKS

Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - eks.amazonaws.com
          Action:
            - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ClusterRole

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: ${EnvironmentName}-ClusterSecurityGroup
        SubnetIds: !Split
          - "|"
          - Fn::ImportValue:
              Fn::Sub: ${EnvironmentName}-AvailableSubnets

Outputs:
  EKSCluster:
    Description: EKS Cluster
    Value: !Ref EKSCluster
    Export:
      Name: !Sub ${EnvironmentName}-EKSCluster
